### CREAR INVENTARIO

POST http://localhost:3000/api/v1/inventario HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiZW1wbGVhZG8iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3NjM1OTEwNjcsImV4cCI6MTc2MzYwOTA2N30.611cvQWe2xAn3FPrh7wQ4d_G-glaoyJSsTjcnNvjTSY

{
  "id_producto": 1,
  "id_empleado": 1,
  "fecha_uso": "2024-09-01T10:00:00"
}


### OBTENER INVENTARIOS

GET http://localhost:3000/api/v1/inventario HTTP/1.1


### OBTENER INVETARIO POR ID

GET http://localhost:3000/api/v1/inventario/1 HTTP/1.1


### ACTUALIZAR UN INVENTARIO ID

PATCH http://localhost:3000/api/v1/inventario/2 HTTP/1.1
Content-Type: application/json

{
   "fecha_uso": "2024-08-01T10:00:00"
}


### ELIMINAR UN INVENTARIO ID

DELETE http://localhost:3000/api/v1/inventario/1 HTTP/1.1
